### ISSUE TITLE
Reduce size of PromethION .html files

### ISSUE THREAD

**Issue by djbutsker** [a-slide/pycoQC#42] opened 2019-01-22 19:51 UTC
The PycoQC .html files are quite large (~500 mb) for a few PromethION summaries that I've run - it would be great to have an option to reduce this size.

**Comment by a-slide** [comment] 2019-01-23 09:58
Hi Daniel,
When used offline the graphing lib plotly stores the data for each plots directly in a embed json structure so you can still interact dynamically with the data. In most of pycoQC plots a random sampling is performed to reduce the compute burden and the amount of data to save. I have to investigate whether it can be further reduced.

**Comment by djbutsker** [comment] 2019-01-23 16:11
Thanks, only an issue for PromethION runs of cDNA where reads go into the 60-70 million range

**Comment by a-slide** [comment] 2019-01-29 11:42
I suppose a possibility would be to give the option to generate a non interactive plot report instead ?
Would that be an acceptable solution ?

**Comment by djbutsker** [comment] 2019-01-29 14:48
That would be great, just an easier way to share the plots outside of a screenshot.

**Comment by a-slide** [comment] 2019-07-24 12:39
Transferred to new issue https://github.com/a-slide/pycoQC/issues/78

**Comment by a-slide** [comment] 2019-07-31 11:19
Actually I just realized that the issue is only caused by the channel activity plot, which is huge for Prom data. I can see that there is an issue as it tries to plot much more channels than the real number. It ends up in storing a massive 2d array. So I have to find out what's wrong here but in the mean time you can plot the report without the channel activity plot by providing a custom configuration file to pycoQC as explain at the end of the CLI usage section in the doc : https://a-slide.github.io/pycoQC/demo/pycoQC_CLI_demo/

**Closed by a-slide** 2019-07-31 11:19 UTC
Labels: enhancement
