### ISSUE TITLE
No module 

### ISSUE THREAD

**Issue by Tdanis** [a-slide/pycoQC#101] opened 2019-10-19 13:01 UTC
Hi, could you suggest me please any solution for this,

Traceback (most recent call last):
  File "pycoQC.py", line 11, in <module>
    from pycoQC.common import *
  File "/home/..../pycoQC/pycoQC.py", line 11, in <module>
    from pycoQC.common import *
ImportError: No module named 'pycoQC.common'; 'pycoQC' is not a package

Thank you

**Comment by a-slide** [comment] 2019-10-22 08:15
I will need more information I you want me to help. Could you please use the issue submission template ?

**Comment by a-slide** [comment] 2019-10-22 08:16
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by Tdanis** [comment] 2019-10-22 08:39
Installation "pip3 install pycoQC" in cluster with linux 16.04, after that everything is ok. 

My command is:

:~/Software/pycoQC$ cd pycoQC
:~/Software/pycoQC/pycoQC$ ls
Barcode_split.py         __main__.py  pycoQC.py        pycoQC_report.py
Fast5_to_seq_summary.py  __pycache__  pycoQC_parse.py  templates
__init__.py              common.py    pycoQC_plot.py

:~/Software/pycoQC/pycoQC$ python3 pycoQC.py 
Traceback (most recent call last):
  File "pycoQC.py", line 11, in <module>
    from pycoQC.common import *
  File "/home1/tdanis/Software/pycoQC/pycoQC/pycoQC.py", line 11, in <module>
    from pycoQC.common import *
ImportError: No module named 'pycoQC.common'; 'pycoQC' is not a package

**Comment by a-slide** [comment] 2019-10-22 08:49
I am not sure I understand what happen, but it is clearly not an error due to pycoQC.
I have the impression that this is something to do with either your installation environment.
Could you retry using a virtual environment as suggested in the installation documentation ?

**Comment by Tdanis** [comment] 2019-10-22 08:58
Yes yes thank you, I will try

**Comment by a-slide** [comment] 2019-11-19 09:47
It has been nearly a month. I assume it is fixed now

**Closed by a-slide** 2019-11-19 09:47 UTC
